### ISSUE TITLE
Add the saml token inside the wssec header

### ISSUE THREAD

**Issue by fpirson** [tilln/jmeter-wssecurity#15]
It will be great if it could be added

**Comment by fpirson** [comment]
see merge request ISSUE-15

**Comment by tilln** [comment]
Please clarify what the challenging part is that this plugin should do;
1. Creating a SAML token, or
2. Signing/encrypting a SAML token, or
3. Adding a SAML token to the WSS header.

I think only 2. makes sense, as 1. can be done statically before the JMeter test run (with timestamps replaced with JMeter variables that will be resolved at run time), and 3. can be done via embedding a JMeter variable in the payload (e.g. `<soap:Header><wsse:Security>${SAML_TOKEN}</wsse:Security></soap:Header>`.

However, 2. would be better implemented as a separate plugin (based on, say, opensaml) rather than as part of this one, as a) wss4j (which this plugin is based on) does not seem to support encrypting SAML tokens (but only [signing](https://github.com/apache/wss4j/blob/wss4j-2.1.8/ws-security-common/src/main/java/org/apache/wss4j/common/saml/SamlAssertionWrapper.java#L487) them) and b) this would introduce additional dependencies.

@fpirson Please comment.
