### ISSUE TITLE
Missing support for "http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p" Key Encryption Algorithm

### ISSUE THREAD

**Issue by kieranmurphy1** [tilln/jmeter-wssecurity#28]
The SOAP Message Encrypter does not support "http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p" as the Key Encryption Algorithm. I am trying to test some predefined security polices in Oracle Web Services Manager which demands the client to use specific algorithms. I am getting the following error: [2019-09-19T10:00:29.601-07:00] [osb_server1] [ERROR] [WSM-00030] [oracle.wsm.resources.security] [tid: [ACTIVE].ExecuteThread: '16' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <anonymous>] [ecid: 60ad4447-d060-4a79-b828-2e2b3eb416ba-00000221,0] [APP: Service Bus Kernel] [partition-name: DOMAIN] [tenant-name: GLOBAL] [FlowId: 0000MpATx8UFw000jzwkno1TWYcM00001B] [oracle.wsm.policy.name: oracle/wss10_message_protection_service_policy] The encryption method key wrap algorithms do not match : Expected : http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p, Actual : http://www.w3.org/2009/xmlenc11#rsa-oaep.

**Comment by tilln** [comment]
This was mistakenly removed with release [1.6](https://github.com/tilln/jmeter-wssecurity/releases/tag/1.6) ([dab38dd](https://github.com/tilln/jmeter-wssecurity/commit/dab38dd7411ecb8a0100eef67a5fb4f48cd5e80c#diff-44c156339e70b0b1cc9fbc9df49c5083L36), rather than replaced with the correct constant as per [wss4j change](https://github.com/apache/wss4j/commit/8d8248a934dbd748abf39c1cdc5bb0b3e15ced2c#diff-5296069c982a9499ad9c4c9c500645d1)) and has been added back in.

Available in [1.8-SNAPSHOT](https://github.com/tilln/jmeter-wssecurity/releases/tag/1.8-SNAPSHOT) until 1.8 is released.
