### ISSUE TITLE
Configure signature key and timestamp in jmeter

### ISSUE THREAD

**Issue by st1983** [tilln/jmeter-wssecurity#32]
Hi am testing micro services using some authentication i. e. signature key and time stamp,now giving input in Header manager. It is valid only 5 minute .I am using input private key and signature generator jar in CMD .Could you pls share me any script for utomatic configuration in jmeter preprocessor.

**Comment by tilln** [comment]
Hi @st1983 

Can you please provide some sample payloads to clarify what exactly you are after?

**Comment by st1983** [comment]
input :Header Manager
Consumer Id
environment type
signature key 
timestamp
Due to company  rule cant share payload details.
My doubt is ,how we can create script for automatic generate signature key and time stamp in jmeter?

**Comment by tilln** [comment]
I understand the payloads may contain confidential or commercially sensitive data, but you could redact those parts and at least share the general structure of your messages?

Since you mention Header Manager, can you confirm whether you are dealing with a SOAP webservice at all, or rather some RESTful API you are passing an authentication token?

Perhaps you could also describe what exactly your "signature generator" jar does that you would want this plugin to do?
