### ISSUE TITLE
SOAP Message Username Token adding nonce / created even if it's false

### ISSUE THREAD

**Issue by rozpiotr** [tilln/jmeter-wssecurity#33]
Add nonce and created = False: 
![conf](https://user-images.githubusercontent.com/25451731/81191107-f0819500-8fb8-11ea-9944-4d286cfc6016.png)
Request contains these values:
![req](https://user-images.githubusercontent.com/25451731/81191114-f1b2c200-8fb8-11ea-8067-90c6d62372a3.png)

**Comment by tilln** [comment]
@rozpiotr Thanks for reporting this.

This is working as [documented](https://github.com/tilln/jmeter-wssecurity#pre-processors)

> Not all setting combinations are valid, and JMeter does not enforce a valid combination to be entered. Instead, invalid ones will cause errors to be logged during runtime.

Reason: 
The wss4j library adds the Nonce and Timestamp for Digest password types, regardless of the configured values in the plugin.

https://github.com/apache/ws-wss4j/blob/wss4j-2.2.2/ws-security-dom/src/main/java/org/apache/wss4j/dom/message/token/UsernameToken.java#L263-L265

```java
           if (passwordType.equals(WSConstants.PASSWORD_DIGEST)) {
                addNonce(doc);
                addCreated(milliseconds, timeSource, doc);
```

If a Digest password without Nonce and/or Timestamp is really required, they will have to be removed from the SOAP message, e.g. via an additional JSR223 Preprocessor.

Dynamically disabling the unsupported or invalid configuration combinations is not possible due to the limited functionality of the JMeter extension framework used.
