### ISSUE TITLE
SOAP Message Signer as a post processor

### ISSUE THREAD

**Issue by nikantsamrit** [tilln/jmeter-wssecurity#37]
Hi,
I am testing a SOAP request with WS-Security enabled. While the request is sent, We are signing and encrypting the request and while receiving response we are Decrypting the response and validating the signature.

I am using WS-security plugin and have added SOAP Message Signer(PreProcessor), SOAP Message Encrypter (PreProcessor) and SOAP Message Decrypter (PostProcessor) in the request. However not sure how to validate the signature for the response.

Can someone please help in creating a plugin or enhancement for SOAP Message Signer as a PostProcessor ?

**Comment by tilln** [comment]
Hi @nikantsamrit 

In addition to decryption, the SOAP Message Decrypter *does* in fact validate the signature and other message parts (e.g. Username and Timestamp tokens).

In order to do that it just needs access to the private key (in "Keystore Settings") and its password (in "Credentials for WSS Processing").

You can verify this by starting JMeter with for example `--loglevel=org.apache.wss4j=DEBUG` and you will find log entries like the below:

```
2020-12-05 12:41:52,174 DEBUG o.a.w.d.v.SignatureTrustValidator: Certificate path has been verified for certificate with subject CN=wssecurity,OU=preprocessor,O=jmeter
2020-12-05 12:41:52,174 DEBUG o.a.w.d.p.SignatureProcessor: Verify XML Signature
```

**Comment by nikantsamrit** [comment]
Hi @tilln ,

I tried the SOAP message Decrypter to validate the signature. In my Jmeter setup I have added two SOAP decrypter, One for Decryption and one for signature validation.  However it didnt work. I am getting an error message saying "No certificate were found for decryption (KeyId)" To make sure my setup is right, We disabled the signature validation in the code and I could see proper decrypted response.
![Signature Validation](https://user-images.githubusercontent.com/29158914/101567141-e633d900-3995-11eb-8424-2210226f1b3c.PNG)

just to inform while sending the request we are signing and encrypting the request and while receiving response we are Decrypting the response and validating the signature.

Please suggest the needful.

**Comment by tilln** [comment]
Hi @nikantsamrit 

1. You should only need one "SOAP Message Decrypter" as it will process the entire WSS header in the message, so it will perform both decryption and validation.
2. The error message indicates a missing certificate ([source](https://github.com/apache/ws-wss4j/blob/wss4j-2.2.2/ws-security-dom/src/main/java/org/apache/wss4j/dom/processor/EncryptedKeyProcessor.java#L185-L190)), so you may want to double check your Decrypter's "Keystore Settings".
3. How exactly did you disable the signature validation? In this plugin's source code, then build a custom version? In any case, this suggests a configuration issue (as above).

It would be helpful if you could provide JMeter debug log output, and possibly your script and/or message payloads.

**Comment by jubinjose** [comment]
@tilln Nikanth meant to say "We disabled the response signing in the code" instead of "We disabled the signature validation in the code"

So yes, with response signing disabled in code, he is able to see the decrypted response. It is just that when response is signed, his jmeter/plugin is unable to validate the signature. Encryption and Signature keys are in the same cert store and he has the correct one. Else decryption would also not work (hence the test case with signature disabled he mentioned)

**Comment by jubinjose** [comment]
But I see what you are saying.
The keys need to be explicitly specified, not just contained within the keystore
So I guess you are asking him to add the signature key also explicitly under the same decryption pro processor he is using?
Will try that

**Comment by jubinjose** [comment]
This worked great.
Thanks @tilln

**Comment by nikantsamrit** [comment]
@tilln thanks a lot for the help. We had two separate Keystore. 1 for response decryption and 1 for Sign validation. We merged both the keys in 1 keystore and that helped.
